#!/bin/sh
mkdir ~/testing
cd ~/testing

git init
git remote add origin git@github.com:InfectedLan/InfectedTest.git
git pull origin master

crontab -l > mycron
echo "*/5 * * * * $HOME/testing/testingCronjob" >> mycron
crontab mycron
rm mycron

chmod +x testingCronjob